config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resource :affiliate_settings
  end

  resources :affiliates, :only => [:show, :index]
end

app/models/spree/affiliate.rb
class Spree::Affiliate < ActiveRecord::Base
  belongs_to :partner,
    class_name: 'Spree::User',
    foreign_key: :partner_id
  belongs_to :user,
    class_name: 'Spree::User'
  has_many :events,
    class_name: 'Spree::AffiliateEvent'

  def name
    I18n.t(:affiliate_program)
  end

  def ref_id
    partner.try(:ref_id) || ''
  end

end

app/models/spree/affiliate_event.rb
class Spree::AffiliateEvent < ActiveRecord::Base
  belongs_to :affiliate,
    class_name: 'Spree::Affiliate'
  belongs_to :reward,
    polymorphic: true
  belongs_to :user,
    class_name: 'Spree::User'

end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  include AffiliateCredits

  alias :old_finalize! :finalize!

  def finalize!
    old_finalize!
    if user && user.affiliate_partner && user.orders.where(state: 'complete').count == 1
      sender = user.referred_by
      create_affiliate_credits(sender, user, 'purchase')
    end
  end

end

app/models/spree/user_decorator.rb
Spree::User.class_eval do

  has_many :affiliates,
    class_name: 'Spree::Affiliate',
    foreign_key: 'partner_id'
  has_many :referred_users,
    class_name: 'Spree::User',
    through: :affiliates,
    source: :user
  has_one :affiliate_partner,
    class_name:'Spree::Affiliate',
    foreign_key: 'user_id'

  def referred_by
    affiliate_partner.try :partner
  end

  def ref_id
    self.id.to_s.reverse
  end

  def ref_token
    Base64.encode64 email
  end

  def self.find_by_ref_id(ref_id)
    Spree::User.find(ref_id.to_s.reverse)
  end
end

app/controllers/spree/admin/affiliate_settings_controller.rb
class Spree::Admin::AffiliateSettingsController < Spree::Admin::BaseController

  def update
    SpreeAffiliate::Config.set(params[:preferences])

    respond_to do |format|
      format.html {
        redirect_to admin_affiliate_settings_path
      }
    end
  end

end

app/controllers/spree/af_controller.rb
module Spree
  class AfController < StoreController
    skip_before_filter  :require_no_authentication

    def show
      @user = User.find_by_ref_id(cookies[:ref_id])
    end
  end
end

app/controllers/spree/affiliates_controller.rb
class Spree::AffiliatesController < Spree::BaseController
  def show
    flash[:notice] = request.flash[:notice]
    redirect_to account_url
  end
end

app/controllers/spree/base_controller_decorator.rb
Spree::BaseController.class_eval do
  before_filter :remember_affiliate

  private
  
  def remember_affiliate
    cookies.permanent[:ref_token] = params[:ref_token] if params[:ref_token]
  end
end

app/controllers/spree/omniauth_callbacks_controller.rb
class Spree::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Spree::Core::ControllerHelpers::Common
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth

  include AffiliateCredits
  

  def self.provides_callback_for(*providers)
    providers.each do |provider|
      class_eval %Q{
        def #{provider}
          if request.env["omniauth.error"].present?
            flash[:error] = t("devise.omniauth_callbacks.failure", :kind => auth_hash['provider'], :reason => t(:user_was_not_valid))
            redirect_back_or_default(root_url)
            return
          end

          authentication = Spree::UserAuthentication.find_by_provider_and_uid(auth_hash['provider'], auth_hash['uid'])

          if authentication.present?
            flash[:notice] = "Signed in successfully"
            sign_in_and_redirect :user, authentication.user
          elsif current_user
            current_user.user_authentications.create!(:provider => auth_hash['provider'], :uid => auth_hash['uid'])
            flash[:notice] = "Authentication successful."
            redirect_back_or_default(account_url)
          else
            user = Spree::User.find_by_email(auth_hash['info']['email']) || Spree::User.new
            user.apply_omniauth(auth_hash)
            if user.save
              @user = user
              check_affiliate
              flash[:notice] = "Signed in successfully."
              sign_in_and_redirect :user, user
            else
              session[:omniauth] = auth_hash.except('extra')
              flash[:notice] = t(:one_more_step, :kind => auth_hash['provider'].capitalize)
              redirect_to new_user_registration_url
            end
          end

          if current_order
            user = current_user if current_user
            current_order.associate_user!(user)
            session[:guest_token] = nil
          end
        end
      }
    end
  end

  SpreeSocial::OAUTH_PROVIDERS.each do |provider|
    provides_callback_for provider[1].to_sym
  end

  def failure
    set_flash_message :alert, :failure, :kind => failed_strategy.name.to_s.humanize, :reason => failure_message
    redirect_to spree.login_path
  end

  def passthru
    render :file => "#{Rails.root}/public/404", :formats => [:html], :status => 404, :layout => false
  end

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/spree/user_registrations_controller_decorator.rb
Spree::UserRegistrationsController.class_eval do
  include AffiliateCredits

  after_action :check_affiliate, only: :create
end

app/controllers/spree/users_controller_decorator.rb
Spree::UsersController.class_eval do
  before_action :find_affiliates, only: :show

  private

  def find_affiliates
    @affiliates ||= current_spree_user.affiliates
  end

end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.class_eval do
  def referral_url(referrer)
    root_url(ref_token: referrer.ref_token)
  end

  def link_to_referral_url(referrer, options = {})
    url = referral_url(referrer)

    link_to(url, url, options)
  end
end

app/views/spree/admin/affiliate_settings/edit.html.haml
= render 'spree/admin/shared/configuration_menu'

%h1= t('affiliate_settings')

= form_tag admin_affiliate_settings_path, method: :put do
  %p
    %label= Spree.t('sender_credit_on_register_amount')
    = text_field_tag('preferences[sender_credit_on_register_amount]',
      SpreeAffiliate::Config[:sender_credit_on_register_amount])
  %p
    %label= Spree.t('recipient_credit_on_register_amount')
    = text_field_tag('preferences[recipient_credit_on_register_amount]',
      SpreeAffiliate::Config[:recipient_credit_on_register_amount])
  %p
    %label= Spree.t('sender_credit_on_purchase_amount')
    = text_field_tag('preferences[sender_credit_on_purchase_amount]',
      SpreeAffiliate::Config[:sender_credit_on_purchase_amount])
  %p
    %label= Spree.t('recipient_credit_on_purchase_amount')
    = text_field_tag('preferences[recipient_credit_on_purchase_amount]',
      SpreeAffiliate::Config[:recipient_credit_on_purchase_amount])

  %p.form-buttons
    = button Spree.t('actions.update')
    = link_to Spree.t('actions.cancel'), admin_affiliate_settings_url

app/views/spree/admin/affiliate_settings/show.html.haml
= render 'spree/admin/shared/configuration_menu'

%h1= t('affiliate_settings')

%table
  %tr
    %th{ scope: 'row'  }
      = Spree.t('sender_credit_on_register_amount')
      \:
    %td= number_to_currency SpreeAffiliate::Config[:sender_credit_on_register_amount]
  %tr
    %th{ scope: 'row' }
      = Spree.t('recipient_credit_on_register_amount')
      \:
    %td= number_to_currency SpreeAffiliate::Config[:recipient_credit_on_register_amount]
  %tr
    %th{ scope: 'row' }
      = Spree.t('sender_credit_on_purchase_amount')
      \:
    %td= number_to_currency SpreeAffiliate::Config[:sender_credit_on_purchase_amount]
  %tr
    %th{ scope: 'row' }
      = Spree.t('recipient_credit_on_purchase_amount')
      \:
    %td= number_to_currency SpreeAffiliate::Config[:recipient_credit_on_purchase_amount]

%p= link_to_with_icon 'edit', Spree.t('actions.edit'), edit_admin_affiliate_settings_path

app/views/spree/af/show.html.erb
<h3><%= t("affiliate.welcome", :store => Spree::Config[:site_name]) -%></h3>

<% if @user %>
  <% if c = SpreeAffiliate::Config[:recipient_credit_on_register_amount] and c > 0 %>
    <%= t("affiliate.description.with_credit", :store => Spree::Config[:site_name], :sender => @user.email, :amount => number_to_currency(SpreeAffiliate::Config[:recipient_credit_on_register_amount])).html_safe %>
  <% else %>
    <%= t("affiliate.description.without_credit", :store => Spree::Config[:site_name], :sender => @user.email, :amount => number_to_currency(SpreeAffiliate::Config[:sender_credit_on_register_amount])) %>
  <% end %>
<% else %>

<% end %>

app/views/spree/affiliates/_affiliate.html.haml
%tr{ class: cycle('even', 'odd') }
  %td= affiliate.user.email
  %td= l affiliate.created_at.to_date

app/views/spree/affiliates/_affiliates.html.haml
.account-my-affiliates{ data: { hook: 'affiliates' } }
  %h3= t(:affiliates_signed_up)

  %strong
    = t('affiliate_link')
  = link_to_referral_url(@user)

  - if @affiliates.present?
    %table
      %thead#my-affiliates
        %tr
          %th= t(:affiliate_email)
          %th= t(:affiliation_date)
      %tbody= render @affiliates
  - else
    %p= t(:no_affiliates_yet)

app/views/spree/affiliates/new.html.erb
<h2>Refer your friends</h2>
<% if current_user %>
  <h5>Share your link with your friend</h5>
  <%= text_field_tag :af_url, af_url(current_user.ref_id) %>
<% else %>
  <h3><%= link_to t(:sign_up), signup_path %> <%= t(:or) %> <%= link_to t(:login), login_path %></h3>
  <h5>to start sharing your link</h5>
<% end %>